beacon.register.path=/secure/search
beacon.poll.path=/secure/update
beacon.register.method=POST
beacon.poll.get.method=GET
beacon.poll.post.method=POST
beacon.token.param=q
beacon.useragent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
beacon.content.type=application/x-www-form-urlencoded
beacon.cookie.name=sessionid
beacon.sleep.ms=8000
beacon.jitter.ms=2000
beacon.max.retry=5
